### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [AutoIt/SublimeAutoItScript#15]
I would like to use your grammar for AutoIt but I don't know what licensing terms you're distributing it under. Any chance you could pick one from here: http://choosealicense.com?

**Comment by jbrooksuk** [comment]
MIT.

**Comment by jbrooksuk** [comment]
https://github.com/AutoIt/SublimeAutoItScript/commit/41171d9b643ea4d99895ecf008fb7d9417ed99ef

**Comment by pchaigno** [comment]
@jbrooksuk That was fast :zap: Thanks!

**Comment by TheDcoder** [comment]
Yeah, Thanks James! :)
