### ISSUE TITLE
Change key bindings

### ISSUE THREAD

**Issue by kien5436** [AutoIt/SublimeAutoItScript#34]
Since `Alt` + `any key` will invoke the menubar function, is there any way to change the key bindings?

**Comment by FichteFoll** [comment]
The package does not define a keymap. The command to run tidy is called `autoittidy` (other commands can be found in the plugin file based on the class names: https://github.com/AutoIt/SublimeAutoItScript/blob/1.3.6/autoitbuild.py).

**Comment by kien5436** [comment]
I don't know about Python, I only want to change key bindings. As I can see in the .py file, I guess `sublime_plugin.WindowCommand` will be invoked but don't know how to change this :/

**Comment by FichteFoll** [comment]
1. Open *Preferences > Key Bindings*
2. Insert this on the right side:

```json
[
    { "keys": ["alt+t", "t"], "command": "autoittidy" },
]
```

(If you already have a list there, only add the object line.)

**Comment by kien5436** [comment]
Thank you! It works :D
